In [93]:
import pandas as pd

In [94]:
data = pd.read_excel("table5.xls",skiprows=3)

data.columns

Index(['State', 'Area', 'Unnamed: 2', 'Population', 'Violent\ncrime1',
       'Murder and \nnonnegligent \nmanslaughter',
       'Rape\n(revised\ndefinition)2 ', 'Rape\n(legacy\ndefinition)3',
       'Robbery', 'Aggravated \nassault', 'Property \ncrime', 'Burglary',
       'Larceny-\ntheft', 'Motor \nvehicle \ntheft'],
      dtype='object')

In [95]:
data
subset = data.drop('State',axis=1)
subset

,Area,Unnamed: 2,Population,Violent crime1,Murder and nonnegligent manslaughter,Rape (revised definition)2,Rape (legacy definition)3,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,Metropolitan Statistical Area,NaN,3708033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Area actually reporting,0.971,18122,283,1496.0,1080.0,4080,12263,113447,27208,78141.0,8098.0
2,NaN,Estimated total,1,18500,287,1537.0,1111.0,4138,12538,115920,27852,79799.0,8269.0
3,Cities outside metropolitan areas,NaN,522241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Area actually reporting,0.974,3178,32,311.0,218.0,354,2481,20873,4438,15106.0,1329.0
5,NaN,Estimated total,1,3240,33,315.0,222.0,360,2532,21203,4518,15329.0,1356.0
6,Nonmetropolitan counties,NaN,628705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Area actually reporting,0.994,1205,28,186.0,122.0,112,879,7578,2868,4004.0,706.0
8,NaN,Estimated total,1,1212,28,187.0,123.0,113,884,7623,2885,4028.0,710.0
9,State Total,NaN,4858979,22952,348,2039.0,1456.0,4611,15954,144746,35255,99156.0,10335.0
10,NaN,"Rate per 100,000 inhabitants",NaN,472.4,7.2,42.0,30.0,94.9,328.3,2978.9,725.6,2040.7,212.7
11,Metropolitan Statistical Area,NaN,351857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Area actually reporting,1,3464,27,541.0,401.0,658,2238,14151,1919,10884.0,1348.0
13,Cities outside metropolitan areas,NaN,127499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Area actually reporting,0.972,886,10,178.0,128.0,60,638,3523,530,2737.0,256.0
15,NaN,Estimated total,1,913,10,184.0,133.0,62,657,3625,545,2817.0,263.0
16,Nonmetropolitan counties,NaN,259076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Area actually reporting,1,1015,22,176.0,116.0,41,776,3030,1047,1548.0,435.0
18,State Total,NaN,738432,5392,59,901.0,650.0,761,3671,20806,3511,15249.0,2046.0
19,NaN,"Rate per 100,000 inhabitants",NaN,730.2,8,122.0,88.0,103.1,497.1,2817.6,475.5,2065.1,277.1
20,Metropolitan Statistical Area,NaN,6479810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,Area actually reporting,0.997,24725,280,2805.0,2072.0,6239,15401,198411,35919,146431.0,16061.0
22,NaN,Estimated total,1,24781,280,2811.0,2077.0,6251,15439,198994,36015,146882.0,16097.0
23,Cities outside metropolitan areas,,124240,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Area actually reporting,0.939,2678,24,269.0,199.0,91,2294,5854,1280,4095.0,479.0
25,NaN,Estimated total,1,2851,26,286.0,210.0,97,2442,6233,1363,4360.0,510.0
26,Nonmetropolitan counties,,224015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Area actually reporting,1,380,3,11.0,7.0,12,354,1880,579,1123.0,178.0
28,State Total,NaN,6828065,28012,309,3108.0,2294.0,6360,18235,207107,37957,152365.0,16785.0
29,NaN,"Rate per 100,000 inhabitants",NaN,410.2,4.5,45.5,33.6,93.1,267.1,3033.2,555.9,2231.5,245.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,NaN,Area actually reporting,0.898,3557,45,402.0,245.0,625,2485,25404,6476,17423.0,1505.0
473,NaN,Estimated total,1,3887,47,433.0,269.0,667,2740,28418,7019,19731.0,1668.0
474,Cities outside metropolitan areas,NaN,189216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,NaN,Area actually reporting,0.53,280,4,23.0,18.0,28,225,1619,264,1285.0,70.0
476,NaN,Estimated total,1,519,8,33.0,26.0,53,425,3056,498,2426.0,132.0
477,Nonmetropolitan counties,NaN,518050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,NaN,Area actually reporting,0.731,1325,11,142.0,83.0,29,1143,4223,1208,2694.0,321.0
479,NaN,Estimated total,1,1825,15,206.0,125.0,40,1564,5777,1653,3685.0,439.0
480,State Total,NaN,1844128,6231,70,672.0,420.0,760,4729,37251,9170,25842.0,2239.0
481,NaN,"Rate per 100,000 inhabitants",NaN,337.9,3.8,36.4,22.8,41.2,256.4,2020,497.3,1401.3,121.4
482,Metropolitan Statistical Area,NaN,4268682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,NaN,Area actually reporting,0.965,15597,207,1368.0,923.0,5087,8935,88714,15012,63592.0,10110.0
484,NaN,Estimated total,1,15770,209,1396.0,945.0,5131,9034,91251,15314,65713.0,10224.0
485,Cities outside metropolitan areas,NaN,639613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,NaN,Area actually reporting,0.938,1015,9,189.0,141.0,79,738,14140,1732,12065.0,343.0
487,NaN,Estimated total,1,1082,10,201.0,150.0,84,787,15070,1846,12858.0,366.0
488,Nonmetropolitan counties,NaN,863042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489,NaN,Area actually reporting,1,795,21,183.0,129.0,17,574,7603,2394,4814.0,395.0
490,State Total,NaN,5771337,17647,240,1780.0,1224.0,5232,10395,113924,19554,83385.0,10985.0
491,NaN,"Rate per 100,000 inhabitants",NaN,305.8,4.2,30.8,21.2,90.7,180.1,1974,338.8,1444.8,190.3
492,Metropolitan Statistical Area,NaN,179738,,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
493,NaN,Area actually reporting,1,366,8,50.0,36.0,31,277,4584,763,3579.0,242.0
494,Cities outside metropolitan areas,NaN,245549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,NaN,Area actually reporting,0.967,629,5,82.0,62.0,24,518,5255,693,4313.0,249.0
496,NaN,Estimated total,1,649,5,83.0,63.0,25,536,5434,717,4460.0,257.0
497,Nonmetropolitan counties,NaN,160820,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN
498,NaN,Area actually reporting,0.916,262,3,35.0,23.0,3,221,1038,258,695.0,85.0
499,NaN,Estimated total,1,287,3,40.0,26.0,3,241,1133,282,758.0,93.0
500,State Total,NaN,586107,1302,16,173.0,125.0,59,1054,11151,1762,8797.0,592.0
501,NaN,"Rate per 100,000 inhabitants",NaN,222.1,2.7,29.5,21.3,10.1,179.8,1902.6,300.6,1500.9,101.0

In [96]:
subset = subset[subset["Area"] == "State Total"].reset_index()
subset

,index,Area,Unnamed: 2,Population,Violent crime1,Murder and nonnegligent manslaughter,Rape (revised definition)2,Rape (legacy definition)3,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,9,State Total,NaN,4858979,22952,348,2039.0,1456.0,4611,15954,144746,35255,99156.0,10335.0
1,18,State Total,NaN,738432,5392,59,901.0,650.0,761,3671,20806,3511,15249.0,2046.0
2,28,State Total,NaN,6828065,28012,309,3108.0,2294.0,6360,18235,207107,37957,152365.0,16785.0
3,39,State Total,NaN,2978204,15526,181,1931.0,1300.0,2098,11316,96836,22640,68424.0,5772.0
4,48,State Total,NaN,39144818,166883,1861,12811.0,9387.0,52862,99349,1024914,197404,656517.0,170993.0
5,59,State Total,NaN,5456574,17515,176,3257.0,2377.0,3323,10759,144136,23454,104682.0,16000.0
6,67,State Total,NaN,3590886,7845,117,773.0,582.0,2892,4063,65066,10053,48675.0,6338.0
7,74,State Total,NaN,945934,4720,63,341.0,243.0,1235,3081,25455,4773,19501.0,1181.0
8,91,State Total,NaN,20271272,93626,1041,7553.0,5430.0,21137,63895,570270,109268,420341.0,40661.0
9,102,State Total,NaN,10214860,38643,615,3224.0,2296.0,12247,22557,308723,66374,215867.0,26482.0
10,109,State Total,,1431603,4201,19,561.0,400.0,1203,2418,54346,6557,42010.0,5779.0
11,118,State Total,NaN,1654930,3568,32,694.0,533.0,192,2650,28858,6124,20863.0,1871.0
12,129,State Total,NaN,12859995,49354,744,4821.0,3549.0,14910,28879,255729,46443,191634.0,17652.0
13,140,State Total,NaN,6619680,25653,373,2404.0,1789.0,7111,15765,171847,34410,123918.0,13519.0
14,150,State Total,NaN,3123899,8936,72,1156.0,851.0,1047,6661,63957,14892,44723.0,4342.0
15,161,State Total,NaN,2911641,11353,128,1615.0,1251.0,1818,7792,79199,15362,56880.0,6957.0
16,170,State Total,NaN,4425092,9676,209,1492.0,997.0,3307,4668,96362,22260,66320.0,7782.0
17,181,State Total,NaN,4670724,25208,481,1723.0,1260.0,5550,17454,156629,35453,111435.0,9741.0
18,189,State Total,NaN,1329328,1729,23,474.0,354.0,311,921,24327,4684,18829.0,814.0
19,197,State Total,NaN,6006401,27462,516,1666.0,1184.0,9863,15417,139048,25678,100219.0,13151.0
20,207,State Total,NaN,6794422,26562,128,2075.0,1608.0,5288,19071,114871,21890,84912.0,8069.0
21,218,State Total,,9922576,41231,571,6450.0,4163.0,7796,26414,187101,40041,131296.0,15764.0
22,226,State Total,NaN,5489594,13319,133,2321.0,1686.0,3771,7094,121984,19299,94704.0,7981.0
23,237,State Total,NaN,2992333,8254,259,1203.0,862.0,2294,4498,84790,24799,55748.0,4243.0
24,247,State Total,NaN,6083672,30261,502,2553.0,1854.0,6376,20830,173642,34006,122637.0,16999.0
25,258,State Total,NaN,1032949,3611,36,547.0,431.0,210,2818,27100,3838,20844.0,2418.0
26,269,State Total,NaN,1896190,5212,62,873.0,652.0,994,3283,42495,6422,32072.0,4001.0
27,277,State Total,NaN,2890845,20118,178,1688.0,1238.0,6287,11965,77137,22360,43426.0,11351.0
28,287,State Total,NaN,1330608,2652,14,627.0,461.0,468,1543,23229,3467,18871.0,891.0
29,293,State Total,NaN,8958013,22879,363,1373.0,1019.0,9729,11414,145701,27960,105963.0,11778.0
30,304,State Total,NaN,2085109,13681,117,1672.0,1215.0,2485,9407,77094,17085,51483.0,8526.0
31,314,State Total,NaN,19795791,75165,609,6074.0,4389.0,23936,44546,317529,44276,257940.0,15313.0
32,325,State Total,NaN,10042802,34852,517,2684.0,1939.0,8825,22826,276183,74841,187907.0,13435.0
33,333,State Total,NaN,756927,1812,21,345.0,276.0,148,1298,16020,2997,11440.0,1583.0
34,344,State Total,NaN,11613423,33898,500,5149.0,4154.0,12554,15695,300525,69303,213993.0,17229.0
35,355,State Total,NaN,3911338,16506,234,1849.0,1352.0,3005,11418,112878,28406,74022.0,10450.0
36,366,State Total,NaN,4028977,10468,99,1593.0,1164.0,2146,6630,118719,18336,89836.0,10547.0
37,376,State Total,NaN,12802503,40339,658,4305.0,3122.0,13003,22373,232085,39664,180287.0,12134.0
38,389,State Total,NaN,1056298,2562,29,459.0,338.0,556,1518,20043,3947,14707.0,1389.0
39,400,State Total,NaN,4896146,24700,399,2297.0,1707.0,3931,18073,161245,34551,113724.0,12970.0
40,411,State Total,NaN,858469,3289,32,495.0,441.0,216,2546,16680,2960,12532.0,1188.0
41,419,State Total,NaN,6600299,40400,406,2676.0,1966.0,7474,29844,193796,43247,137679.0,12870.0
42,430,State Total,NaN,27469114,113227,1316,12250.0,8925.0,31934,67727,777739,153054,557200.0,67485.0
43,441,State Total,NaN,2995919,7071,54,1645.0,1098.0,1326,4046,89278,12468,68103.0,8707.0
44,449,State Total,NaN,626042,739,10,136.0,121.0,101,492,8806,1968,6660.0,178.0
45,459,State Total,NaN,8382993,16399,383,2340.0,1493.0,4441,9235,156470,21340,127019.0,8111.0
46,469,State Total,NaN,7170351,20394,211,2705.0,2193.0,5449,12029,248369,50993,170509.0,26867.0
47,480,State Total,NaN,1844128,6231,70,672.0,420.0,760,4729,37251,9170,25842.0,2239.0
48,490,State Total,NaN,5771337,17647,240,1780.0,1224.0,5232,10395,113924,19554,83385.0,10985.0
49,500,State Total,NaN,586107,1302,16,173.0,125.0,59,1054,11151,1762,8797.0,592.0

In [97]:
states = pd.DataFrame(data['State'].dropna())
states = states['State'].str.replace('\d+', '')
states = pd.DataFrame(states)
states = states[states["State"]!="PUERTO RICO"]
states = states[states["State"]!="DISTRICT OF COLUMBIA"]
states = states.reset_index().drop('index',axis=1)
states

             State
0          ALABAMA
1           ALASKA
2          ARIZONA
3         ARKANSAS
4       CALIFORNIA
5         COLORADO
6      CONNECTICUT
7         DELAWARE
8          FLORIDA
9          GEORGIA
10          HAWAII
11           IDAHO
12        ILLINOIS
13         INDIANA
14            IOWA
15          KANSAS
16        KENTUCKY
17       LOUISIANA
18           MAINE
19        MARYLAND
20   MASSACHUSETTS
21        MICHIGAN
22       MINNESOTA
23     MISSISSIPPI
24        MISSOURI
25         MONTANA
26        NEBRASKA
27          NEVADA
28   NEW HAMPSHIRE
29      NEW JERSEY
30      NEW MEXICO
31        NEW YORK
32  NORTH CAROLINA
33    NORTH DAKOTA
34            OHIO
35        OKLAHOMA
36          OREGON
37    PENNSYLVANIA
38    RHODE ISLAND
39  SOUTH CAROLINA
40    SOUTH DAKOTA
41       TENNESSEE
42           TEXAS
43            UTAH
44         VERMONT
45        VIRGINIA
46      WASHINGTON
47   WEST VIRGINIA
48       WISCONSIN
49         WYOMING

In [98]:
merged = states.merge(subset,left_index=True,right_index=True)
merged = merged.drop(['index','Area','Unnamed: 2','Rape\n(legacy\ndefinition)3'],axis=1)
merged.columns = merged.columns.str.replace('\d+', '')
merged

,State,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA,4858979,22952,348,2039.0,4611,15954,144746,35255,99156.0,10335.0
1,ALASKA,738432,5392,59,901.0,761,3671,20806,3511,15249.0,2046.0
2,ARIZONA,6828065,28012,309,3108.0,6360,18235,207107,37957,152365.0,16785.0
3,ARKANSAS,2978204,15526,181,1931.0,2098,11316,96836,22640,68424.0,5772.0
4,CALIFORNIA,39144818,166883,1861,12811.0,52862,99349,1024914,197404,656517.0,170993.0
5,COLORADO,5456574,17515,176,3257.0,3323,10759,144136,23454,104682.0,16000.0
6,CONNECTICUT,3590886,7845,117,773.0,2892,4063,65066,10053,48675.0,6338.0
7,DELAWARE,945934,4720,63,341.0,1235,3081,25455,4773,19501.0,1181.0
8,FLORIDA,20271272,93626,1041,7553.0,21137,63895,570270,109268,420341.0,40661.0
9,GEORGIA,10214860,38643,615,3224.0,12247,22557,308723,66374,215867.0,26482.0
10,HAWAII,1431603,4201,19,561.0,1203,2418,54346,6557,42010.0,5779.0
11,IDAHO,1654930,3568,32,694.0,192,2650,28858,6124,20863.0,1871.0
12,ILLINOIS,12859995,49354,744,4821.0,14910,28879,255729,46443,191634.0,17652.0
13,INDIANA,6619680,25653,373,2404.0,7111,15765,171847,34410,123918.0,13519.0
14,IOWA,3123899,8936,72,1156.0,1047,6661,63957,14892,44723.0,4342.0
15,KANSAS,2911641,11353,128,1615.0,1818,7792,79199,15362,56880.0,6957.0
16,KENTUCKY,4425092,9676,209,1492.0,3307,4668,96362,22260,66320.0,7782.0
17,LOUISIANA,4670724,25208,481,1723.0,5550,17454,156629,35453,111435.0,9741.0
18,MAINE,1329328,1729,23,474.0,311,921,24327,4684,18829.0,814.0
19,MARYLAND,6006401,27462,516,1666.0,9863,15417,139048,25678,100219.0,13151.0
20,MASSACHUSETTS,6794422,26562,128,2075.0,5288,19071,114871,21890,84912.0,8069.0
21,MICHIGAN,9922576,41231,571,6450.0,7796,26414,187101,40041,131296.0,15764.0
22,MINNESOTA,5489594,13319,133,2321.0,3771,7094,121984,19299,94704.0,7981.0
23,MISSISSIPPI,2992333,8254,259,1203.0,2294,4498,84790,24799,55748.0,4243.0
24,MISSOURI,6083672,30261,502,2553.0,6376,20830,173642,34006,122637.0,16999.0
25,MONTANA,1032949,3611,36,547.0,210,2818,27100,3838,20844.0,2418.0
26,NEBRASKA,1896190,5212,62,873.0,994,3283,42495,6422,32072.0,4001.0
27,NEVADA,2890845,20118,178,1688.0,6287,11965,77137,22360,43426.0,11351.0
28,NEW HAMPSHIRE,1330608,2652,14,627.0,468,1543,23229,3467,18871.0,891.0
29,NEW JERSEY,8958013,22879,363,1373.0,9729,11414,145701,27960,105963.0,11778.0
30,NEW MEXICO,2085109,13681,117,1672.0,2485,9407,77094,17085,51483.0,8526.0
31,NEW YORK,19795791,75165,609,6074.0,23936,44546,317529,44276,257940.0,15313.0
32,NORTH CAROLINA,10042802,34852,517,2684.0,8825,22826,276183,74841,187907.0,13435.0
33,NORTH DAKOTA,756927,1812,21,345.0,148,1298,16020,2997,11440.0,1583.0
34,OHIO,11613423,33898,500,5149.0,12554,15695,300525,69303,213993.0,17229.0
35,OKLAHOMA,3911338,16506,234,1849.0,3005,11418,112878,28406,74022.0,10450.0
36,OREGON,4028977,10468,99,1593.0,2146,6630,118719,18336,89836.0,10547.0
37,PENNSYLVANIA,12802503,40339,658,4305.0,13003,22373,232085,39664,180287.0,12134.0
38,RHODE ISLAND,1056298,2562,29,459.0,556,1518,20043,3947,14707.0,1389.0
39,SOUTH CAROLINA,4896146,24700,399,2297.0,3931,18073,161245,34551,113724.0,12970.0
40,SOUTH DAKOTA,858469,3289,32,495.0,216,2546,16680,2960,12532.0,1188.0
41,TENNESSEE,6600299,40400,406,2676.0,7474,29844,193796,43247,137679.0,12870.0
42,TEXAS,27469114,113227,1316,12250.0,31934,67727,777739,153054,557200.0,67485.0
43,UTAH,2995919,7071,54,1645.0,1326,4046,89278,12468,68103.0,8707.0
44,VERMONT,626042,739,10,136.0,101,492,8806,1968,6660.0,178.0
45,VIRGINIA,8382993,16399,383,2340.0,4441,9235,156470,21340,127019.0,8111.0
46,WASHINGTON,7170351,20394,211,2705.0,5449,12029,248369,50993,170509.0,26867.0
47,WEST VIRGINIA,1844128,6231,70,672.0,760,4729,37251,9170,25842.0,2239.0
48,WISCONSIN,5771337,17647,240,1780.0,5232,10395,113924,19554,83385.0,10985.0
49,WYOMING,586107,1302,16,173.0,59,1054,11151,1762,8797.0,592.0

In [99]:
merged.head()

,State,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA,4858979,22952,348,2039.0,4611,15954,144746,35255,99156.0,10335.0
1,ALASKA,738432,5392,59,901.0,761,3671,20806,3511,15249.0,2046.0
2,ARIZONA,6828065,28012,309,3108.0,6360,18235,207107,37957,152365.0,16785.0
3,ARKANSAS,2978204,15526,181,1931.0,2098,11316,96836,22640,68424.0,5772.0
4,CALIFORNIA,39144818,166883,1861,12811.0,52862,99349,1024914,197404,656517.0,170993.0

In [100]:
merged.columns

Index(['State', 'Population', 'Violent\ncrime',
       'Murder and \nnonnegligent \nmanslaughter',
       'Rape\n(revised\ndefinition) ', 'Robbery', 'Aggravated \nassault',
       'Property \ncrime', 'Burglary', 'Larceny-\ntheft',
       'Motor \nvehicle \ntheft'],
      dtype='object')

In [101]:
for i in range(0,50):
    for name in merged.ix[:,"Violent\ncrime":]:
        merged.ix[i,name] = merged.ix[i,name]/100000

In [102]:
merged

,State,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA,4858979,0.22952,0.00348,0.02039,0.04611,0.15954,1.44746,0.35255,0.99156,0.10335
1,ALASKA,738432,0.05392,0.00059,0.00901,0.00761,0.03671,0.20806,0.03511,0.15249,0.02046
2,ARIZONA,6828065,0.28012,0.00309,0.03108,0.0636,0.18235,2.07107,0.37957,1.52365,0.16785
3,ARKANSAS,2978204,0.15526,0.00181,0.01931,0.02098,0.11316,0.96836,0.2264,0.68424,0.05772
4,CALIFORNIA,39144818,1.66883,0.01861,0.12811,0.52862,0.99349,10.2491,1.97404,6.56517,1.70993
5,COLORADO,5456574,0.17515,0.00176,0.03257,0.03323,0.10759,1.44136,0.23454,1.04682,0.16000
6,CONNECTICUT,3590886,0.07845,0.00117,0.00773,0.02892,0.04063,0.65066,0.10053,0.48675,0.06338
7,DELAWARE,945934,0.0472,0.00063,0.00341,0.01235,0.03081,0.25455,0.04773,0.19501,0.01181
8,FLORIDA,20271272,0.93626,0.01041,0.07553,0.21137,0.63895,5.7027,1.09268,4.20341,0.40661
9,GEORGIA,10214860,0.38643,0.00615,0.03224,0.12247,0.22557,3.08723,0.66374,2.15867,0.26482
10,HAWAII,1431603,0.04201,0.00019,0.00561,0.01203,0.02418,0.54346,0.06557,0.42010,0.05779
11,IDAHO,1654930,0.03568,0.00032,0.00694,0.00192,0.0265,0.28858,0.06124,0.20863,0.01871
12,ILLINOIS,12859995,0.49354,0.00744,0.04821,0.1491,0.28879,2.55729,0.46443,1.91634,0.17652
13,INDIANA,6619680,0.25653,0.00373,0.02404,0.07111,0.15765,1.71847,0.3441,1.23918,0.13519
14,IOWA,3123899,0.08936,0.00072,0.01156,0.01047,0.06661,0.63957,0.14892,0.44723,0.04342
15,KANSAS,2911641,0.11353,0.00128,0.01615,0.01818,0.07792,0.79199,0.15362,0.56880,0.06957
16,KENTUCKY,4425092,0.09676,0.00209,0.01492,0.03307,0.04668,0.96362,0.2226,0.66320,0.07782
17,LOUISIANA,4670724,0.25208,0.00481,0.01723,0.0555,0.17454,1.56629,0.35453,1.11435,0.09741
18,MAINE,1329328,0.01729,0.00023,0.00474,0.00311,0.00921,0.24327,0.04684,0.18829,0.00814
19,MARYLAND,6006401,0.27462,0.00516,0.01666,0.09863,0.15417,1.39048,0.25678,1.00219,0.13151
20,MASSACHUSETTS,6794422,0.26562,0.00128,0.02075,0.05288,0.19071,1.14871,0.2189,0.84912,0.08069
21,MICHIGAN,9922576,0.41231,0.00571,0.06450,0.07796,0.26414,1.87101,0.40041,1.31296,0.15764
22,MINNESOTA,5489594,0.13319,0.00133,0.02321,0.03771,0.07094,1.21984,0.19299,0.94704,0.07981
23,MISSISSIPPI,2992333,0.08254,0.00259,0.01203,0.02294,0.04498,0.8479,0.24799,0.55748,0.04243
24,MISSOURI,6083672,0.30261,0.00502,0.02553,0.06376,0.2083,1.73642,0.34006,1.22637,0.16999
25,MONTANA,1032949,0.03611,0.00036,0.00547,0.0021,0.02818,0.271,0.03838,0.20844,0.02418
26,NEBRASKA,1896190,0.05212,0.00062,0.00873,0.00994,0.03283,0.42495,0.06422,0.32072,0.04001
27,NEVADA,2890845,0.20118,0.00178,0.01688,0.06287,0.11965,0.77137,0.2236,0.43426,0.11351
28,NEW HAMPSHIRE,1330608,0.02652,0.00014,0.00627,0.00468,0.01543,0.23229,0.03467,0.18871,0.00891
29,NEW JERSEY,8958013,0.22879,0.00363,0.01373,0.09729,0.11414,1.45701,0.2796,1.05963,0.11778
30,NEW MEXICO,2085109,0.13681,0.00117,0.01672,0.02485,0.09407,0.77094,0.17085,0.51483,0.08526
31,NEW YORK,19795791,0.75165,0.00609,0.06074,0.23936,0.44546,3.17529,0.44276,2.57940,0.15313
32,NORTH CAROLINA,10042802,0.34852,0.00517,0.02684,0.08825,0.22826,2.76183,0.74841,1.87907,0.13435
33,NORTH DAKOTA,756927,0.01812,0.00021,0.00345,0.00148,0.01298,0.1602,0.02997,0.11440,0.01583
34,OHIO,11613423,0.33898,0.005,0.05149,0.12554,0.15695,3.00525,0.69303,2.13993,0.17229
35,OKLAHOMA,3911338,0.16506,0.00234,0.01849,0.03005,0.11418,1.12878,0.28406,0.74022,0.10450
36,OREGON,4028977,0.10468,0.00099,0.01593,0.02146,0.0663,1.18719,0.18336,0.89836,0.10547
37,PENNSYLVANIA,12802503,0.40339,0.00658,0.04305,0.13003,0.22373,2.32085,0.39664,1.80287,0.12134
38,RHODE ISLAND,1056298,0.02562,0.00029,0.00459,0.00556,0.01518,0.20043,0.03947,0.14707,0.01389
39,SOUTH CAROLINA,4896146,0.247,0.00399,0.02297,0.03931,0.18073,1.61245,0.34551,1.13724,0.12970
40,SOUTH DAKOTA,858469,0.03289,0.00032,0.00495,0.00216,0.02546,0.1668,0.0296,0.12532,0.01188
41,TENNESSEE,6600299,0.404,0.00406,0.02676,0.07474,0.29844,1.93796,0.43247,1.37679,0.12870
42,TEXAS,27469114,1.13227,0.01316,0.12250,0.31934,0.67727,7.77739,1.53054,5.57200,0.67485
43,UTAH,2995919,0.07071,0.00054,0.01645,0.01326,0.04046,0.89278,0.12468,0.68103,0.08707
44,VERMONT,626042,0.00739,0.0001,0.00136,0.00101,0.00492,0.08806,0.01968,0.06660,0.00178
45,VIRGINIA,8382993,0.16399,0.00383,0.02340,0.04441,0.09235,1.5647,0.2134,1.27019,0.08111
46,WASHINGTON,7170351,0.20394,0.00211,0.02705,0.05449,0.12029,2.48369,0.50993,1.70509,0.26867
47,WEST VIRGINIA,1844128,0.06231,0.0007,0.00672,0.0076,0.04729,0.37251,0.0917,0.25842,0.02239
48,WISCONSIN,5771337,0.17647,0.0024,0.01780,0.05232,0.10395,1.13924,0.19554,0.83385,0.10985
49,WYOMING,586107,0.01302,0.00016,0.00173,0.00059,0.01054,0.11151,0.01762,0.08797,0.00592

In [106]:
merged.to_csv('2015_crimerates_bystate.csv')